sudo: false
language: php
php:
 - 5.6

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - hiptest-publisher -c phpunit.conf --only=tests --test-run-id=13586

script:
 - phpunit tests/ProjectTest.php --log-junit results.xml

after_script:
  - hiptest-publisher -c phpunit.conf --push=results.xml --test-run-id=13586

